s=set()
x1=int(input("enter the number"))
x2=int(input("enter the number"))
x3=int(input("enter the number"))
x4=int(input("enter the number"))
x5=int(input("enter the number"))
x6=int(input("enter the number"))
x7=int(input("enter the number"))
x8=int(input("enter the number"))
s.add(x1)
s.add(x2)
s.add(x3)
s.add(x4)
s.add(x5)
s.add(x6)
s.add(x7)
s.add(x8)
print(s)